---
# -- NodeLocal DNS Cache Daemonset Image
image:
  repository: rancher/hardened-dns-node-cache
  pullPolicy: IfNotPresent
  tag: 1.22.28-build20240125

# -- NodeLocal DNS Cache Daemonset Container Image Args
nodelocal:
  container:
    args:
      - -upstreamsvc
      - kube-dns-upstream
      - -skipteardown=true
      - -setupinterface=false
      - -setupiptables=false
# -- NodeLocal DNS Cache Daemonset Config Configmap values
  config:
    zones:
      cluster.local:53:
        plugins:
          errors: true
          cache:
            parameters: 30
            sucess:
              size: 9984
            denial:
              size: 9984
          reload: true
          loop: true
          bind: 0.0.0.0
          forward:
            parameters: __PILLAR__CLUSTER__DNS__  # defaults to /etc/resolv.conf
            force_tcp: true
          prometheus: true
          health: true
      in-addr.arpa:53:
        plugins:
          errors: true
          cache:
            parameters: 30
          reload: true
          loop: true
          bind: 0.0.0.0
          log:
            format: combined
            classes: all
          forward:
            parameters: __PILLAR__CLUSTER__DNS__  # defaults to /etc/resolv.conf
            force_tcp: true
          prometheus: true
      ip6.arpa:53:
        plugins:
          errors: true
          cache:
            parameters: 30
          reload: true
          loop: true
          bind: 0.0.0.0
          log:
            format: combined
            classes: all
          forward:
            parameters: __PILLAR__CLUSTER__DNS__  # defaults to /etc/resolv.conf
            force_tcp: true
          prometheus: true
      .:53:
        plugins:
          errors: true
          cache:
            parameters: 30
          reload: true
          loop: true
          bind: 0.0.0.0
          forward:
            parameters: /etc/resolv.conf
          prometheus: true
        # hosts:
        #   entries:     # dns.hosts INLINE
        #     - ip: 10.5.0.4
        #       name: blabla.lala
        #   ttl: 3600       # in seconds, 3600 (default)
        #   no_reverse: true    # set no_reverse
        #   reload: "0s"    # 0s disable (default), use duration notation, ie, "1.5h"
        #   fallthrough: true

imagePullSecrets: []

cilium:
  enabled: true
  localDnsIp: 169.254.20.11
  clusterDNSService: rke2-coredns-rke2-coredns
  clusterDNSNamespace: ""  # defaults to kube-system
  udp:
    portName: ""  # defaults to dns
  tcp:
    portName: ""  # defaults to dns-tcp

# useHostNetwork is always false when using cilium
useHostNetwork: false

updateStrategy:
  rollingUpdate:
    maxUnavailable: 10%

priorityClassName: system-node-critical
podAnnotations: {}
podSecurityContext: {}

securityContext:
  privileged: true

serviceAccount:
  create: true
  annotations: {}
  name: ""

nodeSelector: {}
affinity: {}

tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists

resources:
  requests:
    cpu: 30m
    memory: 50Mi

metrics:
  prometheusScrape: "true"
  port: 9253

podmonitor:
  enabled: true
  additionalLabels:
    prometheus: rancher-monitoring-prometheus
  annotations: {}
  metricRelabelings: []
